//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Optovik.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public string ByersName { get; set; }
        public int Count { get; set; }
        public decimal Summa { get; set; }
    
        public virtual Byer Byer { get; set; }
        public virtual Product Product { get; set; }
    }
}
